name: dapla-hurtigstart
channels:
  - conda-forge
dependencies:
  - git
  - jupyter-packaging>=0.10.0,<2
  - jupyterlab=3
  - nodejs=16
  - pytest
  - pytest-check-links
  - python=3
  - yarn
  - pip
  - pip:
     - "git+https://github.com/statisticsnorway/hack2022-dapla-hurtigstart@main"
